#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

/**
 * Commands.
 */
function listIssues()
{
    $response = client()->issue->all([
        'assigned_to_id' => 'me',
        'limit' => 30,
    ]);

    $issues = collect($response['issues'])
        ->sortBy('project');

    $issues->map(function ($issue) {
        echo "\n"
            .'    #'.blank($issue['id'], 10)
            .blank($issue['project']['name'], 18)
            .blank($issue['status']['name'], 15)
            .blank($issue['priority']['name'], 10)
            .blank($issue['author']['name'], 24)
            .blank($issue['assigned_to']['name'], 22)
            .blank(substr($issue['created_on'], 0, 10), 12)
            .substr($issue['subject'], 0, 100);
    });
}

function show($issue)
{
    $response = client()->issue->show($issue);
    echo "\n"
    .'   Issue: '.$issue
    ."\n".' Project: '.$response['issue']['project']['name']
    ."\n".' Tracker: '.$response['issue']['tracker']['name']
    ."\n".'  Status: '.$response['issue']['status']['name']
    ."\n".'Priority: '.$response['issue']['priority']['name']
    ."\n".'  Author: '.$response['issue']['author']['name'] . '(' . $response['issue']['author']['id'] . ')'
    ."\n".'Assigned: '.$response['issue']['assigned_to']['name'] . '(' . $response['issue']['assigned_to']['id'] . ')'
    ."\n".'    Date: '.(new Carbon\Carbon($response['issue']['created_on']))->format('d/m/Y')
    ."\n".'    Time: '.(new Carbon\Carbon($response['issue']['created_on']))->format('H:i:s')
    ."\n".' Subject: '.$response['issue']['subject']
    ."\n"
    ."\n".' '.$response['issue']['description']
    ."\n";
}

function open($issue)
{
    $command = 'x-www-browser '.getenv('REDMINE_HOST').'/issues/'.$issue;
    shell_exec($command);
}

function help()
{
    echo <<<HELP

    REDMINE COMMAND LINE TOOL

    enviorment:
        REDMINE_USERNAME Username for login
        REDMINE_PASSWORD Password for login
        REDMINE_HOST     Host of redmine server

    commands:
        help        Print this help message
        show        Show information about a issue
        open        Open the issue in default browser
        list        Print this help message
HELP;
    echo "\n";
}

/**
 * Help functions.
 */
function client()
{
    return new Redmine\Client(getenv('REDMINE_HOST'), getenv('REDMINE_USERNAME'), getenv('REDMINE_PASSWORD'));
}

function blank($text, $number)
{
    return $text.str_repeat(' ', ($number - strlen($text)));
}

function arg($arg)
{
    global $argv;
    if (!in_array($arg, $argv)) {
        return null;
    }

    $index = array_search($arg, $argv);
    if (array_key_exists($index + 1, $argv)) {
        return $argv[$index + 1];
    }

    return true;
}

/*
 * Handler
 */

if ($argc == 1 || in_array('list', $argv)) {
    return listIssues();
}

if ($issue = arg('show')) {
    return show($issue);
}

if ($issue = arg('open')) {
    return open($issue);
}

if (in_array('--help', $argv) || in_array('-h', $argv) || in_array('help', $argv)) {
    return help();
}

echo "Error: command not found, see 'help' for more info. \n";
exit(1);
